spring:
  datasource:
    url: jdbc:mysql://47.98.183.132:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: sier1988
    driver-class-name: com.mysql.cj.jdbc.Driver

#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#---------------------------------------
# MyBatis配置
#---------------------------------------
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.dwc.tranmanagement.dao
server:
  port: 9090